development: &defaults
  adapter: postgresql
  database: sportsbook_api
  host: localhost
  username: hoitomt
  password: badger
  encoding: unicode
  pool: 15

test:
  <<: *defaults
  database: sportsbook_api_test
  min_message: WARNING